# Generated by Django 2.2.10 on 2021-04-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ответ текстом', 'text'), ('ответ с выбором одного варианта', 'one_choose'), ('ответ с выбором нескольких вариантов', 'many_choose')], max_length=100)),
            ],
        ),
    ]
