# Generated by Django 2.2.10 on 2021-04-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_questionoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='question_option',
            field=models.ManyToManyField(related_name='question', to='interview.QuestionOption'),
        ),
    ]
