# Generated by Django 2.2.10 on 2021-04-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_auto_20210430_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='quiz', to='interview.Quiz'),
        ),
    ]
