# Generated by Django 2.2.10 on 2021-04-30 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0008_auto_20210430_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='question',
            new_name='questions',
        ),
    ]
