# Generated by Django 2.2.10 on 2021-04-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0009_auto_20210430_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='quiz', to='interview.Question'),
        ),
    ]
