# Generated by Django 2.2.10 on 2021-05-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0012_quiz_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
