# Generated by Django 2.2.10 on 2021-05-01 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0013_quiz_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOfResearch',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('passed_quiz', models.ManyToManyField(related_name='user_id', to='interview.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('question', models.ManyToManyField(related_name='answer', to='interview.Question')),
                ('quiz', models.ManyToManyField(related_name='answer', to='interview.Quiz')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='interview.UserOfResearch')),
            ],
        ),
    ]
