# Generated by Django 2.2.10 on 2021-05-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0014_answer_userofresearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userofresearch',
            name='passed_quiz',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_id', to='interview.Quiz'),
        ),
    ]
