# Generated by Django 2.2.10 on 2021-05-02 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0015_auto_20210501_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='interview.Question'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='answer',
            name='quiz',
        ),
        migrations.AddField(
            model_name='answer',
            name='quiz',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='interview.Quiz'),
            preserve_default=False,
        ),
    ]
